import { createHmac } from "crypto"

import { faker } from "@faker-js/faker"

/**
 * Computes a valid Svix-standard HMAC-SHA256 signature for the given
 * parameters, returning the full `v1,<base64>` string.
 *
 * @param secret - The webhook signing secret (with or without `whsec_` prefix)
 * @param svixId - The Svix message ID header value
 * @param svixTimestamp - The Svix timestamp header value
 * @param body - The raw request body string
 *
 * @returns The computed signature in `v1,<base64>` format
 *
 * @example
 * const secret = "whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw"
 * const svixId = "msg_a1b2c3d4e5f6g7h8i9j0k"
 * const svixTimestamp = "1700000000"
 * const body = JSON.stringify({ type: "example.event", data: { id: "123" } })
 * const signature = signature(secret, svixId, svixTimestamp, body)
 *
 * This will compute the HMAC-SHA256 signature of the string "msg_a1b2c3d4e5f6g7h8i9j0k.1700000000.{body}" using the provided secret key, and return it in the format "v1,<base64-encoded-signature>".
 */
const signature = (
  secret: string,
  svixId: string,
  svixTimestamp: string,
  body: string,
  prefix = "v1",
): string => {
  const keyBase64 = secret.startsWith("whsec_") ? secret.slice(6) : secret
  const key = Buffer.from(keyBase64, "base64")
  const signedContent = `${svixId}.${svixTimestamp}.${body}`
  const signature = createHmac("sha256", key)
    .update(signedContent)
    .digest("base64")
  return `${prefix},${signature}`
}

/**
 * Generates a random Svix message ID string, which consists of the prefix
 * "msg_" followed by 21 alphanumeric characters.
 *
 * @param prefix - Optional prefix for the message ID (default: "msg_")
 *
 * @returns A random Svix message ID string
 *
 * @example
 * const randomId = id() // e.g. "msg_a1b2c3d4e5f6g7h8i9j0k"
 * const customPrefixId = id("evt_") // e.g. "evt_a1b2c3d4e5f6g7h8i9j0k"
 */
const id = (prefix = "msg_"): string =>
  `${prefix}${faker.string.alphanumeric(21)}`

/**
 * Generates a Svix timestamp string, which is the number of seconds since the
 * Unix epoch (January 1, 1970). By default, it generates a timestamp for a
 * recent date, but you can also provide a specific Date object to generate
 * a timestamp for that date.
 *
 * Note: The generated timestamp is in seconds, so the Date object's time is divided by 1000 and rounded down to the nearest whole number.
 * This ensures that the timestamp is compatible with Svix's expected format for webhook signatures.
 * If you want to generate a timestamp for the current time, simply call `timestamp()` without any arguments, and it will use a recent date generated by Faker.
 *
 * @param date - Optional Date object to generate the timestamp for (default: a recent date)
 *
 * @return A Svix timestamp string representing the number of seconds since the Unix epoch
 *
 * @example
 * const recentTimestamp = timestamp() // e.g. "1700000000"
 * const specificTimestamp = timestamp(new Date("2024-01-01T00:00:00Z")) // "1704067200"
 *
 */
const timestamp = (date = faker.date.recent()): string =>
  Math.floor(date.getTime() / 1000).toString()

/**
 * Generates a random webhook signing secret string in the format expected by Svix.
 * The secret consists of an optional prefix (default: "whsec_") followed by a random alphanumeric string of a specified length (default: 32 characters).
 *
 * @param prefix - Optional prefix for the secret (default whsec_). Svix webhook secrets typically start with "whsec_", but you can customize this if needed.
 * @param postfixLength - The length of the random alphanumeric string that follows the prefix (default: 32 characters). This should be long enough to provide sufficient entropy for security purposes.
 *
 * @return A randomly generated webhook signing secret string in the format "{prefix}{randomString}"
 *
 * @example
 * const randomSecret = secret()
 * // e.g. "whsec_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
 */
const secret = ({ prefix = "whsec_", postfixLength = 32 } = {}): string =>
  `${prefix}${faker.string.alphanumeric({ length: postfixLength })}`

export const factories = { signature, id, timestamp, secret }
