---
engines:
  # Exclude Semgrep rules from test packages which
  # often have unchecked database queries, passwords
  # etc in them.
  opengrep:
    exclude_paths:
      - "**/*.spec.ts"
      - "**/*.e2e-spec.ts"
      - "**/*.ui-spec.ts"
      - "**/specs/**"
      - "**/ui-specs/**"
      - "**/fixtures/**"
      - "packages/docker/**"
      - "packages/fixtures/**"
      - "packages/google-fixtures/**"
      - "packages/mailpit/**"
      - "packages/managed-app/**"
      - "packages/managed-database/**"
      - "packages/minio/**"
      - "packages/mockserver/**"
    exclude_rules:
      - "Semgrep_rules_lgpl_javascript_database_rule-node-nosqli-injection"
