import { type DynamicModule, Module } from "@nestjs/common"

import {
  ConfigurableModuleClass,
  type OPTIONS_TYPE,
} from "./healthcheck.module-definition"

/**
 * NestJS dynamic module that wires up the healthcheck infrastructure:
 * `HealthService` (the primary injectable), `ProbeRunnerService` (internal,
 * executes the configured upstream probes), and `HealthcheckInterceptor`
 * (registered globally via `APP_INTERCEPTOR`).
 *
 * Import once in the consuming `AppModule`. Not `@Global()` — the
 * `APP_INTERCEPTOR` registration is process-wide regardless, and
 * `HealthService` is only needed where it's explicitly imported.
 *
 * Both `forRoot()` (zero-arg supported — produces the v0.2.0 wire shape
 * verbatim) and `forRootAsync()` (for config-driven probe URLs) are
 * generated by `ConfigurableModuleBuilder`.
 *
 * @example
 * ```ts
 * @Module({
 *   imports: [
 *     HealthcheckModule.forRoot({
 *       probes: [
 *         { name: "storage", url: `${process.env.S3_ENDPOINT}/minio/health/live` },
 *         { name: "mail", url: "https://api.resend.com/health", timeout: 3000 },
 *       ],
 *     }),
 *   ],
 * })
 * export class AppModule {}
 * ```
 */
@Module({})
export class HealthcheckModule extends ConfigurableModuleClass {
  /**
   * Overrides the builder-generated `forRoot` to permit a zero-arg call,
   * preserving the v0.2.0 wire shape verbatim. The
   * `ConfigurableModuleBuilder`'s default `omitExtras` step calls
   * `Object.keys(input)` and throws on `undefined`, so we coerce missing
   * options to `{}` before delegating.
   */
  public static forRoot(options: typeof OPTIONS_TYPE = {}): DynamicModule {
    return super.forRoot(options)
  }
}
